### ISSUE TITLE
examples don't work

### ISSUE THREAD

**Issue by marwahaha** [entropicalabs/entropica_qaoa#6]
I think it has to do with `QAOACostFunctionOnWFSim`. I am following the first steps tutorial. When I try to `minimize` this cost function, I get
> WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27e1dd1cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /qvm

Why would this code call out to another service? Can the minimization be done locally?

**Comment by jlbosse** [comment]
Did you install and are you running Rigettis QVM and quilc compiler? We use them as a simulator backend and they need to run in the background, as described in the second paragraph of the [documentation](https://docs.entropicalabs.io/qaoa/notebooks/1_anexampleworkflow). Installation instructions are found [on Rigettis website](https://pyquil-docs.rigetti.com/en/stable/start.html)

**Comment by marwahaha** [comment]
Ah, thank you!
